### ISSUE TITLE
启动时无法连接到服务器会导致游戏崩溃

### ISSUE THREAD

**Issue by block13566** [Cong0707/multiplayer#3]
MDT版本146，Android，学术端

以下为学术端给出的崩溃报告
`喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
学术版本: 30815
系统: Linux xnull (aarch64)
Android API level: 30
Java版本: 0
可用内存: 256mb
核心数量: 8
Mods: multiplayer:2

> Runtime: 'Error loading mod multiplayer'
Mods.contextRun: 4
Mods.lambda$eachClass$30: 6
Mods.$r8$lambda$2CoIO8ODCJQS22NT6qOYJY14n_U: 0
Mods$$ExternalSyntheticLambda4.get: 30
Seq.each: 2
Mods.eachClass: 12
ClientLauncher.update: 13
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1577
GLSurfaceView$GLThread.run: 1272
> UnknownHost: 'Unable to resolve host "p4.simpfun.cn": No address associated with hostname'
Inet6AddressImpl.lookupHostByName: 156
Inet6AddressImpl.lookupAllHostAddr: 103
InetAddress.getAllByName: 1152
Dns$1.lookup: 41
RouteSelector.resetNextInetSocketAddress: 178
RouteSelector.nextProxy: 144
RouteSelector.next: 86
StreamAllocation.findConnection: 176
StreamAllocation.findHealthyConnection: 128
StreamAllocation.newStream: 97
HttpEngine.connect: 289
HttpEngine.sendRequest: 232
HttpURLConnectionImpl.execute: 465
HttpURLConnectionImpl.getResponse: 411
HttpURLConnectionImpl.getInputStream: 248
URL.openStream: 1073
TextStreamsKt.readBytes: 155
ManageRoomsDialog.loadURL: 68
ManageRoomsDialog.<init>: 64
Main.init: 16
Vars$$ExternalSyntheticLambda1.get: 8
Mods.lambda$eachClass$29: 2
Mods.$r8$lambda$zrybw-oMfGj3D42fv15WRAprNaY: 0
Mods$$ExternalSyntheticLambda13.run: 26
Mods.contextRun: 1
Mods.lambda$eachClass$30: 6
Mods.$r8$lambda$2CoIO8ODCJQS22NT6qOYJY14n_U: 0
Mods$$ExternalSyntheticLambda4.get: 30
Seq.each: 2
Mods.eachClass: 12
ClientLauncher.update: 13
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1577
GLSurfaceView$GLThread.run: 1272
> Gai: 'android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)'
Linux.android_getaddrinfo: -2
ForwardingOs.android_getaddrinfo: 73
BlockGuardOs.android_getaddrinfo: 202
ForwardingOs.android_getaddrinfo: 73
Inet6AddressImpl.lookupHostByName: 135
Inet6AddressImpl.lookupAllHostAddr: 103
InetAddress.getAllByName: 1152
Dns$1.lookup: 41
RouteSelector.resetNextInetSocketAddress: 178
RouteSelector.nextProxy: 144
RouteSelector.next: 86
StreamAllocation.findConnection: 176
StreamAllocation.findHealthyConnection: 128
StreamAllocation.newStream: 97
HttpEngine.connect: 289
HttpEngine.sendRequest: 232
HttpURLConnectionImpl.execute: 465
HttpURLConnectionImpl.getResponse: 411
HttpURLConnectionImpl.getInputStream: 248
URL.openStream: 1073
TextStreamsKt.readBytes: 155
ManageRoomsDialog.loadURL: 68
ManageRoomsDialog.<init>: 64
Main.init: 16
Vars$$ExternalSyntheticLambda1.get: 8
Mods.lambda$eachClass$29: 2
Mods.$r8$lambda$zrybw-oMfGj3D42fv15WRAprNaY: 0
Mods$$ExternalSyntheticLambda13.run: 26
Mods.contextRun: 1
Mods.lambda$eachClass$30: 6
Mods.$r8$lambda$2CoIO8ODCJQS22NT6qOYJY14n_U: 0
Mods$$ExternalSyntheticLambda4.get: 30
Seq.each: 2
Mods.eachClass: 12
ClientLauncher.update: 13
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1577
GLSurfaceView$GLThread.run: 1272
`

**Comment by Cong0707** [comment]
修好了 启动不再自动获取服务器列表
